### ISSUE TITLE
Cannot compile the data

### ISSUE THREAD

**Issue by LiamDawe** [signus-game/signus#12]
Hi, trying to compile this on Arch Linux with the data (as per the instructions) doesn't seem to work.

This is from a fresh git clone:

> [liam@liam-pc signus-data]$ make
> Making all in utils
> make[1]: Entering directory '/home/liam/signus/signus-data/utils'
> g++ -DPACKAGE_NAME=\"signus-data\" -DPACKAGE_TARNAME=\"signus-data\" -DPACKAGE_VERSION=\"1.96\" -DPACKAGE_STRING=\"signus-data\ 1.96\" -DPACKAGE_BUGREPORT=\"vslavik@fastmail.fm\" -DPACKAGE_URL=\"\" -DPACKAGE=\"signus-data\" -DVERSION=\"1.96\" -I.     -g -O2 -MT makedat.o -MD -MP -MF .deps/makedat.Tpo -c -o makedat.o makedat.cpp
> makedat.cpp:47:25: error: reference to ‘byte’ is ambiguous
>    47 |                         byte Terrain;        // prvn� level
>       |                         ^~~~
> In file included from /usr/include/c++/11.1.0/bits/stl_algobase.h:61,
>                  from /usr/include/c++/11.1.0/bits/char_traits.h:39,
>                  from /usr/include/c++/11.1.0/ios:40,
>                  from /usr/include/c++/11.1.0/ostream:38,
>                  from /usr/include/c++/11.1.0/iostream:39,
>                  from makedat.cpp:16:
> /usr/include/c++/11.1.0/bits/cpp_type_traits.h:404:30: note: candidates are: ‘enum class std::byte’
>   404 |   enum class byte : unsigned char;
>       |                              ^~~~
> In file included from makedat.cpp:18:
> fonts.h:14:23: note:                 ‘typedef unsigned char byte’
>    14 | typedef unsigned char byte;
>       |                       ^~~~
> makedat.cpp:48:25: error: reference to ‘byte’ is ambiguous
>    48 |                         byte Terrain2;       // druh� �rove� ter�nu
>       |                         ^~~~
> In file included from /usr/include/c++/11.1.0/bits/stl_algobase.h:61,
>                  from /usr/include/c++/11.1.0/bits/char_traits.h:39,
>                  from /usr/include/c++/11.1.0/ios:40,
>                  from /usr/include/c++/11.1.0/ostream:38,
>                  from /usr/include/c++/11.1.0/iostream:39,
>                  from makedat.cpp:16:
> /usr/include/c++/11.1.0/bits/cpp_type_traits.h:404:30: note: candidates are: ‘enum class std::byte’
>   404 |   enum class byte : unsigned char;
>       |                              ^~~~
> In file included from makedat.cpp:18:
> fonts.h:14:23: note:                 ‘typedef unsigned char byte’
>    14 | typedef unsigned char byte;
>       |                       ^~~~
> makedat.cpp:49:25: error: reference to ‘byte’ is ambiguous
>    49 |                         byte Unit;           // where 0xFF = none
>       |                         ^~~~
> In file included from /usr/include/c++/11.1.0/bits/stl_algobase.h:61,
>                  from /usr/include/c++/11.1.0/bits/char_traits.h:39,
>                  from /usr/include/c++/11.1.0/ios:40,
>                  from /usr/include/c++/11.1.0/ostream:38,
>                  from /usr/include/c++/11.1.0/iostream:39,
>                  from makedat.cpp:16:
> /usr/include/c++/11.1.0/bits/cpp_type_traits.h:404:30: note: candidates are: ‘enum class std::byte’
>   404 |   enum class byte : unsigned char;
>       |                              ^~~~
> In file included from makedat.cpp:18:
> fonts.h:14:23: note:                 ‘typedef unsigned char byte’
>    14 | typedef unsigned char byte;
>       |                       ^~~~
> makedat.cpp:50:25: error: reference to ‘byte’ is ambiguous
>    50 |                         byte Height    : 3;  // v��ka ter�nu (0..7)
>       |                         ^~~~
> In file included from /usr/include/c++/11.1.0/bits/stl_algobase.h:61,
>                  from /usr/include/c++/11.1.0/bits/char_traits.h:39,
>                  from /usr/include/c++/11.1.0/ios:40,
>                  from /usr/include/c++/11.1.0/ostream:38,
>                  from /usr/include/c++/11.1.0/iostream:39,
>                  from makedat.cpp:16:
> /usr/include/c++/11.1.0/bits/cpp_type_traits.h:404:30: note: candidates are: ‘enum class std::byte’
>   404 |   enum class byte : unsigned char;
>       |                              ^~~~
> In file included from makedat.cpp:18:
> fonts.h:14:23: note:                 ‘typedef unsigned char byte’
>    14 | typedef unsigned char byte;
>       |                       ^~~~
> makedat.cpp:51:25: error: reference to ‘byte’ is ambiguous
>    51 |                         byte IsAnim    : 1;  // je to animovan�?
>       |                         ^~~~
> In file included from /usr/include/c++/11.1.0/bits/stl_algobase.h:61,
>                  from /usr/include/c++/11.1.0/bits/char_traits.h:39,
>                  from /usr/include/c++/11.1.0/ios:40,
>                  from /usr/include/c++/11.1.0/ostream:38,
>                  from /usr/include/c++/11.1.0/iostream:39,
>                  from makedat.cpp:16:
> /usr/include/c++/11.1.0/bits/cpp_type_traits.h:404:30: note: candidates are: ‘enum class std::byte’
>   404 |   enum class byte : unsigned char;
>       |                              ^~~~
> In file included from makedat.cpp:18:
> fonts.h:14:23: note:                 ‘typedef unsigned char byte’
>    14 | typedef unsigned char byte;
>       |                       ^~~~
> makedat.cpp:52:25: error: reference to ‘byte’ is ambiguous
>    52 |                         byte Visib     : 2;  // viditelnost 00-nic, 01-�ed�, 11-pln�
>       |                         ^~~~
> In file included from /usr/include/c++/11.1.0/bits/stl_algobase.h:61,
>                  from /usr/include/c++/11.1.0/bits/char_traits.h:39,
>                  from /usr/include/c++/11.1.0/ios:40,
>                  from /usr/include/c++/11.1.0/ostream:38,
>                  from /usr/include/c++/11.1.0/iostream:39,
>                  from makedat.cpp:16:
> /usr/include/c++/11.1.0/bits/cpp_type_traits.h:404:30: note: candidates are: ‘enum class std::byte’
>   404 |   enum class byte : unsigned char;
>       |                              ^~~~
> In file included from makedat.cpp:18:
> fonts.h:14:23: note:                 ‘typedef unsigned char byte’
>    14 | typedef unsigned char byte;
>       |                       ^~~~
> make[1]: *** [Makefile:406: makedat.o] Error 1
> make[1]: Leaving directory '/home/liam/signus/signus-data/utils'
> make: *** [Makefile:362: all-recursive] Error 1

**Comment by dpanter** [comment]
Builds and plays OK on Siduction (Debian sid), [build log](https://gist.github.com/dpanter/e98b354d7cebae6cc72fc36dd41fc233)

Had to install `libsdl2-ttf-dev libsdl2-image-dev libjpeg-dev` and also `make install` needs **sudo**, no other issues found.

**Comment by nextghost** [comment]
I've pushed a fix. Update your copy and try again.

**Comment by LiamDawe** [comment]
Nice one! Fixed.
