### ISSUE TITLE
Flathub version of the game not saving

### ISSUE THREAD

**Issue by ILikePigeons** [signus-game/signus#24]
I don't know if this is the right place to report this issue, if it isn't I will remove the post.

The Flathub version of the game doesn't save the settings and games. After restarting the game, saved games are gone and settings are back to default ones.

Fixes that I've found so far are to either give Signus access to the **~/.signus** directory or adding **.signus** as a path created in the sandbox (ie. on the Persistent tab in Flatseal.)

Both of these fix this issue and both saved games and settings are saved.

**Comment by nextghost** [comment]
Sorry, I don't maintain the Signus flatpack. You probably want to report this in flathub/flathub#4472. You can also have a look whether your favorite distro provides Signus as a regular package or you can build the game from source. Gentoo ebuild and RPM specfiles are in the git repo.

**Comment by ILikePigeons** [comment]
Ok, thanks. I wasn't sure where to post this issue, so thank you for sending me the link. I am thinking about maybe building from the source for the heck of it. However, I generally prefer just installing packages normally, as updating the software built from the source is kinda annoying to me, due to the fact that I would have to uninstall it and then install the newer version (unless the software can be updated automatically).

**Comment by ILikePigeons** [comment]
Alright, the issue has been fixed. 👍🏻
